const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const INPUT_PATH = path.join(ROOT, "data", "d1_enriched_all_seasons.js");
const MANIFEST_PATH = path.join(ROOT, "data", "vendor", "d1_year_manifest.js");
const CHUNK_DIR = path.join(ROOT, "data", "vendor", "d1_year_chunks");

function parseCSV(text) {
  const rows = [];
  if (!text) return rows;
  let current = "";
  let row = [];
  let inQuotes = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];
    if (char === "\"") {
      if (inQuotes && next === "\"") {
        current += "\"";
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === "," && !inQuotes) {
      row.push(current);
      current = "";
      continue;
    }

    if ((char === "\n" || char === "\r") && !inQuotes) {
      if (char === "\r" && next === "\n") index += 1;
      row.push(current);
      current = "";
      if (row.length > 1 || row[0] !== "") rows.push(row);
      row = [];
      continue;
    }

    current += char;
  }

  row.push(current);
  if (row.length > 1 || row[0] !== "") rows.push(row);
  return rows;
}

function escapeCsvValue(value) {
  const raw = value == null ? "" : String(value);
  if (!/[",\r\n]/.test(raw)) return raw;
  return `"${raw.replace(/"/g, '""')}"`;
}

function encodeCsv(rows) {
  return rows.map((row) => row.map(escapeCsvValue).join(",")).join("\n");
}

function extractCsvString(source) {
  const match = source.match(/^window\.D1_ENRICHED_ALL_CSV = "([\s\S]*)";\s*$/);
  if (!match) {
    throw new Error("Could not find the D1 CSV payload in data/d1_enriched_all_seasons.js");
  }
  return match[1].replace(/\\n/g, "\n").replace(/\\"/g, "\"").replace(/\\\\/g, "\\");
}

function main() {
  const source = fs.readFileSync(INPUT_PATH, "utf8");
  const csvText = extractCsvString(source);
  const rows = parseCSV(csvText);
  if (rows.length < 2) throw new Error("D1 CSV payload is unexpectedly small");

  const header = rows[0];
  const seasonIndex = header.indexOf("season");
  if (seasonIndex < 0) throw new Error("D1 CSV payload has no season column");

  const grouped = new Map();
  for (const row of rows.slice(1)) {
    const season = String(row[seasonIndex] || "").trim();
    if (!season) continue;
    if (!grouped.has(season)) grouped.set(season, []);
    grouped.get(season).push(row);
  }

  const years = Array.from(grouped.keys()).sort((left, right) => Number(left) - Number(right));
  const latestYear = years[years.length - 1];

  fs.mkdirSync(CHUNK_DIR, { recursive: true });

  const manifest = {
    years,
    latestYear,
    initialYears: [latestYear],
    rowCounts: Object.fromEntries(years.map((year) => [year, grouped.get(year).length])),
  };

  fs.writeFileSync(
    MANIFEST_PATH,
    [
      "// Generated by build_d1_mobile_chunks.js",
      `// ${new Date().toISOString()}`,
      `window.D1_YEAR_MANIFEST = ${JSON.stringify(manifest, null, 2)};`,
      "",
    ].join("\n"),
    "utf8"
  );

  for (const year of years) {
    const seasonRows = [header, ...grouped.get(year)];
    const csvChunk = encodeCsv(seasonRows);
    const output = [
      "// Generated by build_d1_mobile_chunks.js",
      `// ${new Date().toISOString()}`,
      `window.D1_YEAR_CSV_CHUNKS = window.D1_YEAR_CSV_CHUNKS || {};`,
      `window.D1_YEAR_CSV_CHUNKS[${JSON.stringify(year)}] = ${JSON.stringify(csvChunk)};`,
      "",
    ].join("\n");
    fs.writeFileSync(path.join(CHUNK_DIR, `${year}.js`), output, "utf8");
  }

  console.log(`Wrote ${years.length} D1 season chunks and manifest to ${CHUNK_DIR}.`);
}

main();
